on: push
name: MyMirror / openharmony-mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror OpenHarmony from Gitee to Github
      uses: ./.
      with:
        src: gitee/openharmony
        dst: github/OpenHarmony-mirror
        dst_key: ${{ secrets.MYGITHUB_PRIVATE_KEY }}
        dst_token: ${{ secrets.MYGITHUB_TOKEN }}
        src_account_type: org
        dst_account_type: user
        force_update: true
        debug: true
        clone_style: https
